# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 1075)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #2e2e2e;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMainWindow::separator {\n"
"    background: #444444;\n"
"    width: 2px;\n"
"    height: 2px;\n"
"}\n"
"\n"
"QMainWindow::separator:hover {\n"
"    background: #555555;\n"
"}\n"
"\n"
"QToolBar {\n"
"    background: #3a3a3a;\n"
"    border: 1px solid #444444;\n"
"    spacing: 3px;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal {\n"
"    image: url(handle.png);\n"
"}\n"
"\n"
"QToolBar::separator {\n"
"    background: #444444;\n"
"    width: 1px;\n"
"    height: 1px;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background: #3a3a3a;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"    padding: 5px 10px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: #4d4d4d;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #3a3a3a;\n"
"    border: 1px solid #444444;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background-color: transparent;\n"
"    padding: 5px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #4d4d4d;\n"
"    color: #dcdcdc;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background: #3a3a3a;\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 1400, 950))
        self.tabWidget.setStyleSheet("QTabWidget::pane { \n"
"    border: 1px solid #444444; \n"
"    background: #2e2e2e;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: #3a3a3a;\n"
"    color: #ffffff;\n"
"    padding: 10px;\n"
"    border: 1px solid #444444;\n"
"    border-bottom: none;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #4d4d4d;\n"
"    border-color: #555555;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; \n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: #5a5a5a;\n"
"    color: #dcdcdc;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.btn_open_file = QtWidgets.QPushButton(self.tab)
        self.btn_open_file.setEnabled(True)
        self.btn_open_file.setGeometry(QtCore.QRect(20, 100, 161, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(240, 240, 240))
        gradient.setColorAt(1.0, QtGui.QColor(224, 224, 224))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(240, 240, 240))
        gradient.setColorAt(1.0, QtGui.QColor(224, 224, 224))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(240, 240, 240))
        gradient.setColorAt(1.0, QtGui.QColor(224, 224, 224))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(240, 240, 240))
        gradient.setColorAt(1.0, QtGui.QColor(224, 224, 224))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(240, 240, 240))
        gradient.setColorAt(1.0, QtGui.QColor(224, 224, 224))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        gradient = QtGui.QLinearGradient(0.0, 0.0, 1.0, 1.0)
        gradient.setSpread(QtGui.QGradient.PadSpread)
        gradient.setCoordinateMode(QtGui.QGradient.ObjectBoundingMode)
        gradient.setColorAt(0.0, QtGui.QColor(240, 240, 240))
        gradient.setColorAt(1.0, QtGui.QColor(224, 224, 224))
        brush = QtGui.QBrush(gradient)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.btn_open_file.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Tahoma,Geneva,Verdana,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_open_file.setFont(font)
        self.btn_open_file.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #f0f0f0, \n"
"                                stop: 1 #e0e0e0);\n"
"    color: #333;\n"
"    border: 2px solid #bbb;\n"
"    border-radius: 8px;\n"
"    padding: 10px 20px;\n"
"    font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    cursor: pointer;\n"
"    transition: background 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #e0e0e0, \n"
"                                stop: 1 #d0d0d0);\n"
"    border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #d0d0d0;\n"
"    border-color: #999;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #f9f9f9;\n"
"    color: #aaa;\n"
"    border: 2px solid #ddd;\n"
"    cursor: not-allowed;\n"
"}\n"
"")
        icon = QtGui.QIcon.fromTheme("1")
        self.btn_open_file.setIcon(icon)
        self.btn_open_file.setCheckable(False)
        self.btn_open_file.setDefault(False)
        self.btn_open_file.setObjectName("btn_open_file")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 20, 321, 61))
        self.label.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #f9f9f9, \n"
"                                stop: 1 #e0e0e0);\n"
"    color: #333;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #e0e0e0, \n"
"                                stop: 1 #d0d0d0);\n"
"    border-color: #ccc;\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background: #e0e0e0;\n"
"    border-color: #bbb;\n"
"}\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/danie/OneDrive/文件/下載 (1).jpg"))
        self.label.setObjectName("label")
        self.label_file_name = QtWidgets.QLabel(self.tab)
        self.label_file_name.setGeometry(QtCore.QRect(200, 100, 571, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Tahoma,Geneva,Verdana,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_file_name.setFont(font)
        self.label_file_name.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #f9f9f9, \n"
"                                stop: 1 #e0e0e0);\n"
"    color: #333;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #e0e0e0, \n"
"                                stop: 1 #d0d0d0);\n"
"    border-color: #ccc;\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background: #e0e0e0;\n"
"    border-color: #bbb;\n"
"}\n"
"")
        self.label_file_name.setObjectName("label_file_name")
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(810, 120, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(230, 480, 211, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.plate_image = QtWidgets.QLabel(self.tab)
        self.plate_image.setGeometry(QtCore.QRect(800, 190, 209, 89))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Tahoma,Geneva,Verdana,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.plate_image.setFont(font)
        self.plate_image.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #212121, \n"
"                                stop: 1 #424242);\n"
"    color: #e0e0e0;\n"
"    border: 1px solid #666;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.5);\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #424242, \n"
"                                stop: 1 #616161);\n"
"    border: 1px solid #888;\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background: #303030;\n"
"    border: 1px solid #555;\n"
"}\n"
"")
        self.plate_image.setText("")
        self.plate_image.setObjectName("plate_image")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 170, 741, 531))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.scrollArea.setFont(font)
        self.scrollArea.setMouseTracking(False)
        self.scrollArea.setTabletTracking(False)
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"    background: #2e2e2e;\n"
"    border: 1px solid #444;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: #3c3c3c;\n"
"    width: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background: #3c3c3c;\n"
"    height: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #6d6d6d;\n"
"    border-radius: 6px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #6d6d6d;\n"
"    border-radius: 6px;\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #888;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed,\n"
"QScrollBar::handle:horizontal:pressed {\n"
"    background: #555;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: 1px solid #444;\n"
"    border-radius: 6px;\n"
"    background: #3c3c3c;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: 1px solid #444;\n"
"    border-radius: 6px;\n"
"    background: #3c3c3c;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: 1px solid #444;\n"
"    border-radius: 6px;\n"
"    background: #3c3c3c;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: 1px solid #444;\n"
"    border-radius: 6px;\n"
"    background: #3c3c3c;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical,\n"
"QScrollBar::left-arrow:horizontal,\n"
"QScrollBar::right-arrow:horizontal {\n"
"    background: #666;\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical:hover,\n"
"QScrollBar::down-arrow:vertical:hover,\n"
"QScrollBar::left-arrow:horizontal:hover,\n"
"QScrollBar::right-arrow:horizontal:hover {\n"
"    background: #888;\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 737, 527))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_img = QtWidgets.QLabel()
        self.label_img.setGeometry(QtCore.QRect(0, 0, 0,0))
        self.label_img.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #212121, \n"
"                                stop: 1 #424242);\n"
"    color: #e0e0e0;\n"
"    border: 1px solid #666;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.5);\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #424242, \n"
"                                stop: 1 #616161);\n"
"    border: 1px solid #888;\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background: #303030;\n"
"    border: 1px solid #555;\n"
"}\n"
"")
        self.label_img.setText("")
        self.label_img.setObjectName("label_img")
        self.scrollArea.setWidget(self.label_img)
        self.verticalLayout.addWidget(self.scrollArea)
        self.plates = QtWidgets.QLabel(self.tab)
        self.plates.setGeometry(QtCore.QRect(1020, 230, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Tahoma,Geneva,Verdana,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.plates.setFont(font)
        self.plates.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #f9f9f9, \n"
"                                stop: 1 #e0e0e0);\n"
"    color: #333;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #e0e0e0, \n"
"                                stop: 1 #d0d0d0);\n"
"    border-color: #ccc;\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background: #e0e0e0;\n"
"    border-color: #bbb;\n"
"}\n"
"")
        self.plates.setObjectName("plates")
        self.running_time = QtWidgets.QLabel(self.tab)
        self.running_time.setGeometry(QtCore.QRect(790, 310, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Tahoma,Geneva,Verdana,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.running_time.setFont(font)
        self.running_time.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #f9f9f9, \n"
"                                stop: 1 #e0e0e0);\n"
"    color: #333;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #e0e0e0, \n"
"                                stop: 1 #d0d0d0);\n"
"    border-color: #ccc;\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background: #e0e0e0;\n"
"    border-color: #bbb;\n"
"}\n"
"")
        self.running_time.setObjectName("running_time")
        self.btn_zoom_in = QtWidgets.QPushButton(self.tab)
        self.btn_zoom_in.setGeometry(QtCore.QRect(40, 730, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Tahoma,Geneva,Verdana,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_zoom_in.setFont(font)
        self.btn_zoom_in.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #f0f0f0, \n"
"                                stop: 1 #e0e0e0);\n"
"    color: #333;\n"
"    border: 2px solid #bbb;\n"
"    border-radius: 8px;\n"
"    padding: 10px 20px;\n"
"    font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    cursor: pointer;\n"
"    transition: background 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #e0e0e0, \n"
"                                stop: 1 #d0d0d0);\n"
"    border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #d0d0d0;\n"
"    border-color: #999;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #f9f9f9;\n"
"    color: #aaa;\n"
"    border: 2px solid #ddd;\n"
"    cursor: not-allowed;\n"
"}\n"
"")
        self.btn_zoom_in.setObjectName("btn_zoom_in")
        self.silder_zoom = QtWidgets.QSlider(self.tab)
        self.silder_zoom.setGeometry(QtCore.QRect(180, 740, 160, 22))
        self.silder_zoom.setStyleSheet("QSlider::groove:horizontal {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, \n"
"                                stop: 0 #003366, \n"
"                                stop: 1 #004080);\n"
"    height: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #0066cc;\n"
"    border: 1px solid #003f5c;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    margin: -6px 0; /* center the handle */\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: #004080;\n"
"    border: 1px solid #001f3f;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed {\n"
"    background: #003366;\n"
"    border: 1px solid #002b36;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, \n"
"                                stop: 0 #001f3f, \n"
"                                stop: 1 #003366);\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0, \n"
"                                stop: 0 #0066cc, \n"
"                                stop: 1 #00bfff);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    background: qlineargradient(y1: 0, x1: 0, y2: 1, x2: 0, \n"
"                                stop: 0 #003366, \n"
"                                stop: 1 #004080);\n"
"    width: 8px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: #0066cc;\n"
"    border: 1px solid #003f5c;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 10px;\n"
"    margin: 0 -6px; /* center the handle */\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"    background: #004080;\n"
"    border: 1px solid #001f3f;\n"
"}\n"
"\n"
"QSlider::handle:vertical:pressed {\n"
"    background: #003366;\n"
"    border: 1px solid #002b36;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background: qlineargradient(y1: 0, x1: 0, y2: 1, x2: 0, \n"
"                                stop: 0 #001f3f, \n"
"                                stop: 1 #003366);\n"
"}\n"
"\n"
"QSlider::sub-page:vertical {\n"
"    background: qlineargradient(y1: 0, x1: 0, y2: 1, x2: 0, \n"
"                                stop: 0 #0066cc, \n"
"                                stop: 1 #00bfff);\n"
"}\n"
"")
        self.silder_zoom.setOrientation(QtCore.Qt.Horizontal)
        self.silder_zoom.setObjectName("silder_zoom")
        self.label__radio = QtWidgets.QLabel(self.tab)
        self.label__radio.setGeometry(QtCore.QRect(510, 740, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label__radio.setFont(font)
        self.label__radio.setObjectName("label__radio")
        self.btn_zoom_out = QtWidgets.QPushButton(self.tab)
        self.btn_zoom_out.setGeometry(QtCore.QRect(370, 730, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Tahoma,Geneva,Verdana,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_zoom_out.setFont(font)
        self.btn_zoom_out.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #f0f0f0, \n"
"                                stop: 1 #e0e0e0);\n"
"    color: #333;\n"
"    border: 2px solid #bbb;\n"
"    border-radius: 8px;\n"
"    padding: 10px 20px;\n"
"    font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    cursor: pointer;\n"
"    transition: background 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #e0e0e0, \n"
"                                stop: 1 #d0d0d0);\n"
"    border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #d0d0d0;\n"
"    border-color: #999;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #f9f9f9;\n"
"    color: #aaa;\n"
"    border: 2px solid #ddd;\n"
"    cursor: not-allowed;\n"
"}\n"
"")
        self.btn_zoom_out.setObjectName("btn_zoom_out")
        self.label_img_shape = QtWidgets.QLabel(self.tab)
        self.label_img_shape.setGeometry(QtCore.QRect(40, 800, 561, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Tahoma,Geneva,Verdana,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_img_shape.setFont(font)
        self.label_img_shape.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #f9f9f9, \n"
"                                stop: 1 #e0e0e0);\n"
"    color: #333;\n"
"    border: 2px solid #ddd;\n"
"    border-radius: 8px;\n"
"    padding: 10px;\n"
"    font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QLabel:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #e0e0e0, \n"
"                                stop: 1 #d0d0d0);\n"
"    border-color: #ccc;\n"
"}\n"
"\n"
"QLabel:pressed {\n"
"    background: #e0e0e0;\n"
"    border-color: #bbb;\n"
"}\n"
"")
        self.label_img_shape.setObjectName("label_img_shape")
        self.btn_execute = QtWidgets.QPushButton(self.tab)
        self.btn_execute.setGeometry(QtCore.QRect(670, 730, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Tahoma,Geneva,Verdana,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_execute.setFont(font)
        self.btn_execute.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #f0f0f0, \n"
"                                stop: 1 #e0e0e0);\n"
"    color: #333;\n"
"    border: 2px solid #bbb;\n"
"    border-radius: 8px;\n"
"    padding: 10px 20px;\n"
"    font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    cursor: pointer;\n"
"    transition: background 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #e0e0e0, \n"
"                                stop: 1 #d0d0d0);\n"
"    border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #d0d0d0;\n"
"    border-color: #999;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #f9f9f9;\n"
"    color: #aaa;\n"
"    border: 2px solid #ddd;\n"
"    cursor: not-allowed;\n"
"}\n"
"")
        self.btn_execute.setObjectName("btn_execute")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(810, 400, 531, 421))
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #f2f2f2, stop: 1 #e0e0e0\n"
"    ); /* 垂直渐变背景 */\n"
"    border: 1px solid #ccc; /* 边框颜色 */\n"
"    gridline-color: #d0d0d0; /* 网格线颜色 */\n"
"    border-radius: 6px; /* 边角圆润 */\n"
"    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); /* 更加明显的阴影效果 */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 6px; /* 单元格内边距 */\n"
"    color: #2c2c2c; /* 字体颜色 */\n"
"    border-radius: 4px; /* 单元格边角圆润 */\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 #ffffff, stop: 1 #f5f5f5\n"
"    ); /* 水平渐变背景 */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 0, y2: 1,\n"
"        stop: 0 #dcdcdc, stop: 1 #c0c0c0\n"
"    ); /* 表头垂直渐变背景 */\n"
"    color: #2c2c2c; /* 表头字体颜色 */\n"
"    border: 1px solid #ccc; /* 表头边框颜色 */\n"
"    border-radius: 4px; /* 表头边角圆润 */\n"
"    padding: 6px; /* 表头内边距 */\n"
"    font-weight: bold; /* 字体加粗 */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 #b3d9ff, stop: 1 #a0c8ff\n"
"    ); /* 选中单元格水平渐变背景 */\n"
"    border: 1px solid #8aaad0; /* 选中单元格边框颜色 */\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0, x2: 1, y2: 0,\n"
"        stop: 0 #e6f7ff, stop: 1 #d0efff\n"
"    ); /* 悬停单元格水平渐变背景 */\n"
"    border: 1px solid #a0bedf; /* 悬停单元格边框颜色 */\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.delete_list = QtWidgets.QPushButton(self.tab)
        self.delete_list.setGeometry(QtCore.QRect(1230, 350, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI,Tahoma,Geneva,Verdana,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.delete_list.setFont(font)
        self.delete_list.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #f0f0f0, \n"
"                                stop: 1 #e0e0e0);\n"
"    color: #333;\n"
"    border: 2px solid #bbb;\n"
"    border-radius: 8px;\n"
"    padding: 10px 20px;\n"
"    font-family: \'Segoe UI\', Tahoma, Geneva, Verdana, sans-serif;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    cursor: pointer;\n"
"    transition: background 0.3s, border-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, \n"
"                                stop: 0 #e0e0e0, \n"
"                                stop: 1 #d0d0d0);\n"
"    border-color: #aaa;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #d0d0d0;\n"
"    border-color: #999;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #f9f9f9;\n"
"    color: #aaa;\n"
"    border: 2px solid #ddd;\n"
"    cursor: not-allowed;\n"
"}\n"
"")
        self.delete_list.setObjectName("delete_list")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(1140, 20, 181, 91))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(110, 120, 1051, 591))
        self.label_2.setObjectName("label_2")
        self.ip = QtWidgets.QTextEdit(self.tab_2)
        self.ip.setGeometry(QtCore.QRect(70, 60, 121, 41))
        self.ip.setObjectName("ip")
        self.port = QtWidgets.QTextEdit(self.tab_2)
        self.port.setGeometry(QtCore.QRect(230, 60, 101, 41))
        self.port.setObjectName("port")
        self.connect = QtWidgets.QPushButton(self.tab_2)
        self.connect.setGeometry(QtCore.QRect(390, 60, 91, 41))
        self.connect.setObjectName("connect")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_open_file.setText(_translate("MainWindow", "select car platees"))
        self.label_file_name.setText(_translate("MainWindow", "file name"))
        self.plates.setText(_translate("MainWindow", "plate number:"))
        self.running_time.setText(_translate("MainWindow", "Runnung time"))
        self.btn_zoom_in.setText(_translate("MainWindow", "zoom_in"))
        self.label__radio.setText(_translate("MainWindow", "TextLabel"))
        self.btn_zoom_out.setText(_translate("MainWindow", "zoom_out"))
        self.label_img_shape.setText(_translate("MainWindow", "TextLabel"))
        self.btn_execute.setText(_translate("MainWindow", "detect"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "辨識時間"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "車牌號碼"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "車牌照片"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "執行時間"))
        self.delete_list.setText(_translate("MainWindow", "delete_list"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "IP_carema"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.connect.setText(_translate("MainWindow", "connect"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Expert_IP_Canera"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
